SignalR json saving
HubertasVin/PSI-1 pull request #8
Opened 2023-09-28 17:45 UTC by Sc0rpie

What has been added:

- Real-time chat is now being saved and loaded upon webpage load.
- For the time being, chat history is being saved in JSON.
- Messages now appear with a timestamp (shows the time when the message was sent).

2023-09-28 17:49 UTC, HubertasVin submitted a review, later dismissed
Ooo, reikia čia biški pratrinti

2023-09-28 17:54 UTC, aWhiteScreen requested changes
Project/InOut/JSONParser.cs should probably be changed a bit. Weird comments and unnecessary in the constructor.

2023-09-28 17:54 UTC, aWhiteScreen commented on Project/InOut/JSONParser.cs
we should consider moving the code from the JSONParser constructor to elsewhere, it's probably bad practice.

2023-09-29 07:44 UTC, aWhiteScreen approved these changes
Looke good now. Approved.

2023-09-29 07:46 UTC, Sc0rpie reviewed
Unnecessary code has been removed.

2023-09-29 12:38 UTC, merged